### ISSUE TITLE
Git Provider "GitBranch" seem not work on Windows

### ISSUE THREAD

**Issue by Julpikar** [glepnir/galaxyline.nvim#135]
Hi, I have tried using  `GitBranch` provider in my galaxyline config but it seem not worked. While other features Git provider like `DiffAdd`, `DiffModified`, `DiffRemove` are working fine. By the way I'm using neovim in Windows 10.

**Comment by at74S6v** [comment]
Same for me, windows 10 with the latest git and doesn't work.

**Comment by l-kershaw** [comment]
From what I can tell, the problem comes from this line: https://github.com/glepnir/galaxyline.nvim/blob/cbf64bd4869c810b92f6450ed8763456c489be87/lua/galaxyline/provider_vcs.lua#L85

On Windows, absolute paths don't start with "/", so `M.get_git_dir(path)` ends up returning the path repeated twice.
I'm not sure what the best way to check if a path is absolute in Windows using Lua is. Does anyone have any ideas?

**Comment by Julpikar** [comment]
Yes it work on my config, thanx!!!.
