### ISSUE TITLE
Add icon_highlight option

### ISSUE THREAD

**Issue by Stanislav-Lapata** [glepnir/galaxyline.nvim#16]
What do you think of this option?
```lua
  AnyName = {
    ...
    icon = '  ',
    icon_highlight = {colors.green, colors.red},
    ...
  }
```

**Comment by glepnir** [comment]
@Stanislav-Lapata  
Hi I designed this keyword in my initial design, but I found that it didn't make much sense. Because you can define a new section to implement it like this, It just makes the section longer. I want to hear the opinions of more people. Do we need this field, it is easy to implement. 
```lua
gls.left[1] = {
   SomeIconFiled = {
         provider = function () return  icon end
          highlight = color in here
}
```

**Comment by Stanislav-Lapata** [comment]
@glepnir You are probably right. Thanks for the quick response

**Comment by bobicino** [comment]
I would find this option useful. The reason is that the separator appears even if the `condition` is false. Instead the icon only if it is true. So, I could use the icon as a separator, just coloring it.

**Comment by glepnir** [comment]
PR welcome :)
