### ISSUE TITLE
Check if telescope is running

### ISSUE THREAD

**Issue by tummetott** [glepnir/galaxyline.nvim#161]
Hello, 

I have a special Statusline only when NvimTree is open. I check for
``vim.bo.filetype == "NvimTree"``
inside a condition of a short line component

I would like to have the same with telescope, but telescope does not change the filetype.
Does anyone know to check with lua if telesope is running?

**Comment by ram02z** [comment]
@Tummetott iirc Telescope does change the filetype to `TelescopePrompt`.

**Comment by Tummetott** [comment]
Are you sure? For me it does not change the filetype at all 😑

**Comment by ram02z** [comment]
@Tummetott might want to file a bug report upstream because its showing up for me.
![image](https://user-images.githubusercontent.com/59267627/117573145-4c03c880-b0ce-11eb-8c83-edbcd27a9c3d.png)

**Comment by Tummetott** [comment]
Ok thanks I’ll investigate further

**Comment by sangdth** [comment]
@Tummetott I don't know, but after playing around with your code, I found out something interesting.

![telescope](https://user-images.githubusercontent.com/1083478/119792421-5996bc00-bede-11eb-92e3-cb365220fde5.gif)

If I open the nvim-tree (the file explorer), and enable the statusline there, now whenever I open/close the Telescope, the TELESCOPE text does toggle over there, but delayed.

So I guess, because the focus already "leave", so it does not update the statusline in the buffer?

Sorry if I cause any confusion. I'm totally new in this area.
