### ISSUE TITLE
FileIcon does not follow custom file icons defined in nvim-webdevicons

### ISSUE THREAD

**Issue by siduck** [glepnir/galaxyline.nvim#174]
Hi there! I have some custom config ( nvim-webdevicons)  for certain file types , but galaxyline doesnt follow that. Other plugins like Nvimtree , nvim-bufferline follows it tho 

Nvimtree : 
![image](https://user-images.githubusercontent.com/59060246/120104013-020f7f00-c170-11eb-9522-162284849ac1.png)

nvim-bufferline : 
![image](https://user-images.githubusercontent.com/59060246/120104018-09cf2380-c170-11eb-846d-43376a3fc04f.png)

webdevicons config : 
![image](https://user-images.githubusercontent.com/59060246/120103983-de4c3900-c16f-11eb-8601-3dfff5bc0455.png)

galaxyline's fileicon : 
![image](https://user-images.githubusercontent.com/59060246/120103936-afce5e00-c16f-11eb-9e1b-1509bb6a368b.png)

**Comment by jedi04** [comment]
It is because icons from  [vim-devicons](https://github.com/ryanoasis/vim-devicons) are used first and if not installed then [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons) is used.

https://github.com/glepnir/galaxyline.nvim/blob/d544cb9d0b56f6ef271db3b4c3cf19ef665940d5/lua/galaxyline/provider_fileinfo.lua#L136-L143

I feel icon loading should be in following order :
1. Custom User Icons 
2. nvim-web-devicons
3. vim--devicons

**Comment by jedi04** [comment]
#175

**Comment by jedi04** [comment]
#175
